const path = require('path');
const fs = require('fs');
const express = require('express');
const credentials = require('./credentials.json');
const { JWT } = require('google-auth-library');
const { GoogleSpreadsheet } = require('google-spreadsheet');
const app = express();
const express = require('express');
const mainAppRouter = require('./routes/mainAppRoutes');
const gSheetsRouter = require('./gSheetsRoutes.js');

const PORT = 1111;
//p
app.get('/api/', async (req, res) => {
  // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
  console.log('test');
  try {
    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: credentials.client_email,
      key: credentials.private_key,
      scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });
    const sheet = new GoogleSpreadsheet(
      '1MI9j-m1jouEMF7GlQ7NF__569_tbCHGRmKaHRtlBRBM',
      serviceAccountAuth,
    );
    await sheet.loadInfo();
  } catch (err) {
    // big error
    fs.writeFileSync('./errDump.json', JSON.stringify(err));
  }
  console.log(sheet.title);
  res.sendStatus(200);
});

//HANDLE parsing body
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

//route handler
app.use('/api', gSheetsRouter);
app.use('/', mainAppRouter);
// app.get('/', (req, res) => {
//   res.status(200).send('Big');
// });

app.listen(PORT, () => {
  console.log(`Server listening on port: ${PORT}...`);
});

//route catch
app.use('*', (req, res) => res.sendStatus(404));

//global error handler
app.use((err, req, res, next) => {
  const errorStatus = err.status || 500;
  const errorLog = err.log;
  return res.status(errorStatus).send(`err: ${err.log}`);
});

module.exports = app;
